I consulted the codebook for what each column .
Qestion is to understand which column to select and how to clean the data here  [https://www.cdc.gov/brfss/annual_data/2015/pdf/codebook15_llcp.pdf](https://www.cdc.gov/brfss/annual_data/2015/pdf/codebook15_llcp.pdf).

Then I selected those relevant to diabetes

In [1]:
# importing necessary libraries 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

***Important Risk Factors***

Selected the following  **risk factors** for diabetes 
*   blood pressure (high)
*   cholesterol (high)
*   smoking
*   diabetes
*   age
*   sex
*   race
*   diet
*   exercise
*   alcohol consumption
*   BMI
*   Household Income
*   Marital Status
*   Sleep
*   Time since last checkup
*   Education
*   Health care coverage
*   Mental Health

## Data info extraction

In [2]:
# columns in dataset  that are important risk factors of diabetes
diabetes_factors = ["DIABETE3","_RFHYPE5","TOLDHI2","_CHOLCHK","_BMI5","SMOKE100",
                    "CVDSTRK3", "_MICHD","_TOTINDA","_FRTLT1", "_VEGLT1", "_RFDRHV5",
                    "HLTHPLN1","MEDCOST","GENHLTH","MENTHLTH","PHYSHLTH","DIFFWALK","SEX",
                    "_AGEG5YR","EDUCA", "INCOME2"]

In [3]:
# original dataset to be used for training, will make copy for EDA.
data = pd.read_csv("../data/raw/2015.csv.zip",usecols=diabetes_factors,compression="zip")

In [4]:
# renaming columns for better readability
data.rename(mapper={"DIABETE3":"Diabetes","_RFHYPE5":"HighBp","TOLDHI2":"HighCholesterol",
                  "_CHOLCHK":"CheckedCholesterol","_BMI5":"BMI","SMOKE100":"Smoke100",
                  "CVDSTRK3":"Stroke","_MICHD":"HeartDisease","_TOTINDA":"PhysicalActivity",
                  "_FRTLT1":"Fruits","_VEGLT1":"Vegetables","_RFDRHV5":"HeavyDrinking",
                  "HLTHPLN1":"HealthCareAccess","MEDCOST":"MedicalCost","GENHLTH":"GeneralHealth",
                  "MENTHLTH":"MentalHealth","PHYSHLTH":"PhysicalHealth","DIFFWALK":"DifficultyWalking",
                  "SEX":"Sex","_AGEG5YR":"Age","EDUCA":"Education","INCOME2":"Income"},axis=1,inplace=True)
print(f"Data shape: {data.shape}")
data.head()

Data shape: (441456, 22)

,GeneralHealth,PhysicalHealth,MentalHealth,HealthCareAccess,MedicalCost,HighCholesterol,Stroke,Diabetes,Sex,Education,...,Smoke100,HighBp,CheckedCholesterol,HeartDisease,Age,BMI,HeavyDrinking,Fruits,Vegetables,PhysicalActivity
0,5.0,15.0,18.0,1.0,2.0,1.0,2.0,3.0,2.0,4.0,...,1.0,2.0,1.0,2.0,9.0,4018.0,1.0,2.0,1.0,2.0
1,3.0,88.0,88.0,2.0,1.0,2.0,2.0,3.0,2.0,6.0,...,1.0,1.0,2.0,2.0,7.0,2509.0,1.0,2.0,2.0,1.0
2,4.0,15.0,88.0,1.0,2.0,1.0,1.0,3.0,2.0,4.0,...,NaN,1.0,1.0,NaN,11.0,2204.0,9.0,9.0,9.0,9.0
3,5.0,30.0,30.0,1.0,1.0,1.0,2.0,3.0,2.0,4.0,...,2.0,2.0,1.0,2.0,9.0,2819.0,1.0,1.0,2.0,2.0
4,5.0,20.0,88.0,1.0,2.0,2.0,2.0,3.0,2.0,5.0,...,2.0,1.0,1.0,2.0,9.0,2437.0,1.0,9.0,1.0,2.0

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 441456 entries, 0 to 441455
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   GeneralHealth       441454 non-null  float64
 1   PhysicalHealth      441455 non-null  float64
 2   MentalHealth        441456 non-null  float64
 3   HealthCareAccess    441456 non-null  float64
 4   MedicalCost         441455 non-null  float64
 5   HighCholesterol     382302 non-null  float64
 6   Stroke              441456 non-null  float64
 7   Diabetes            441449 non-null  float64
 8   Sex                 441456 non-null  float64
 9   Education           441456 non-null  float64
 10  Income              438155 non-null  float64
 11  DifficultyWalking   429122 non-null  float64
 12  Smoke100            427201 non-null  float64
 13  HighBp              441456 non-null  float64
 14  CheckedCholesterol  441456 non-null  float64
 15  HeartDisease        437514 non-null  float64
 16  Age                 441456 non-null  float64
 17  BMI                 405058 non-null  float64
 18  HeavyDrinking       441456 non-null  float64
 19  Fruits              441456 non-null  float64
 20  Vegetables          441456 non-null  float64
 21  PhysicalActivity    441456 non-null  float64
dtypes: float64(22)
memory usage: 74.1 MB

In [6]:
data.describe()

,GeneralHealth,PhysicalHealth,MentalHealth,HealthCareAccess,MedicalCost,HighCholesterol,Stroke,Diabetes,Sex,Education,...,Smoke100,HighBp,CheckedCholesterol,HeartDisease,Age,BMI,HeavyDrinking,Fruits,Vegetables,PhysicalActivity
count,441454.000000,441455.000000,441456.000000,441456.000000,441455.000000,382302.000000,441456.000000,441449.000000,441456.000000,441456.000000,...,427201.000000,441456.000000,441456.000000,437514.000000,441456.000000,405058.000000,441456.000000,441456.000000,441456.000000,441456.000000
mean,2.578790,60.655113,64.679178,1.101201,1.916066,1.630876,1.973880,2.757888,1.576542,4.920094,...,1.613987,1.428410,1.533609,1.911699,7.803623,2804.242400,1.516312,2.131746,2.109316,1.931871
std,1.117585,37.055684,35.843085,0.512261,0.415414,0.740235,0.348689,0.723319,0.494107,1.076198,...,0.746530,0.646749,1.555462,0.283733,3.495609,665.463433,1.874580,2.322882,2.522517,2.209728
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1202.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,15.000000,28.000000,1.000000,2.000000,1.000000,2.000000,3.000000,1.000000,4.000000,...,1.000000,1.000000,1.000000,2.000000,5.000000,2373.000000,1.000000,1.000000,1.000000,1.000000
50%,2.000000,88.000000,88.000000,1.000000,2.000000,2.000000,2.000000,3.000000,2.000000,5.000000,...,2.000000,1.000000,1.000000,2.000000,8.000000,2695.000000,1.000000,1.000000,1.000000,1.000000
75%,3.000000,88.000000,88.000000,1.000000,2.000000,2.000000,2.000000,3.000000,2.000000,6.000000,...,2.000000,2.000000,1.000000,2.000000,10.000000,3090.000000,1.000000,2.000000,2.000000,2.000000
max,9.000000,99.000000,99.000000,9.000000,9.000000,9.000000,9.000000,9.000000,2.000000,9.000000,...,9.000000,9.000000,9.000000,2.000000,14.000000,9995.000000,9.000000,9.000000,9.000000,9.000000

In [7]:
continuous_cols = ["BMI", "MentalHealth", "PhysicalHealth"]

binary_cols = [
    "HighBp","HighCholesterol","Smoke100","Stroke","HeartDisease","PhysicalActivity","Fruits","Vegetables",
    "HeavyDrinking","HealthCareAccess","MedicalCost","DifficultyWalking","Sex"
]

ordinal_cols = ["GeneralHealth","Age","Education","Income"]
nominal_cols = ["CheckedCholesterol"]

In [8]:
data["CheckedCholesterol"].value_counts()

CheckedCholesterol
1.0    362923
3.0     49673
9.0     15337
2.0     13523
Name: count, dtype: int64

In [ ]:
# defined codes in the dataset that represent missing values from the codebook
missing_codes = {
    "Diabetes": [7,9],
    "HighBp": [9],
    "HighCholesterol": [7,9],
    "Smoke100": [7,9],
    "Stroke": [7,9],
    "PhysicalActivity": [9],
    "Fruits": [9],
    "Vegetables": [9],
    "HeavyDrinking": [9],
    "HealthCareAccess": [7,9],
    "MedicalCost": [7,9],
    "GeneralHealth": [7,9],
    "MentalHealth": [77,99],
    "PhysicalHealth": [77,99],
    "DifficultyWalking": [7,9],
    "Age": [14],
    "Education": [9],
    "Income": [77,99]
}

In [ ]:
for col, codes in missing_codes.items():
    data[col] = data[col].replace({c:np.nan for c in codes})

In [ ]:
# total number of null values in each column
data.isnull().sum()

In [ ]:
# scaling BMI down by 100 to get actual BMI values
data["BMI"] = (data["BMI"].div(100)).round(2)
# Replacing 88  with 0 in MentalHealth(good mental health) and PhysicalHealth columns
data["MentalHealth"] = data["MentalHealth"].replace({88:0})
data["PhysicalHealth"] = data["PhysicalHealth"].replace({88:0})

## Preprocessing

In [ ]:
# Dealing with only diabetes or no diabetes for now 
data = data[data["Diabetes"].isin([1, 3])]
data["Diabetes"] = data["Diabetes"].map({1:1, 3:0})
# checking for duplicates 
print(data.duplicated().value_counts())

In [ ]:
# removing duplicates to prevent data leakage and ensure data integrity
data.drop_duplicates(inplace=True)

In [ ]:
# mapping nominal column values to answer to question asked in codebook
data["CheckedCholesterol"] = data["CheckedCholesterol"].map({1:"recently",2:"not_recently",3:"never",9:"unknown"})

In [ ]:
# Reversing  the  ordinal scale of GeneralHealth for consistency:
data["GeneralHealth"] = data["GeneralHealth"].map({1:5,2:4,3:3,4:2,5:1})
# now poor becomes 1 and excellent becomes 5, which is more intuitive to me.

In [ ]:
#  structuring right Binary encoding order for binary columns to ensure consistency and interpretability across the dataset
data["DifficultyWalking"] = data["DifficultyWalking"].replace({1:1,2:0})
data["Sex"] = data["Sex"].replace({1:1,2:0})
data["HeavyDrinking"] = data["HeavyDrinking"].replace({1:0,2:1})
data["HealthCareAccess"] = data["HealthCareAccess"].replace({1:1,2:0})
data["MedicalCost"] = data["MedicalCost"].replace({1:1,2:0})
data["PhysicalActivity"] = data["PhysicalActivity"].replace({1:1,2:0})
data["Fruits"] = data["Fruits"].replace({1:1,2:0})
data["Vegetables"] = data["Vegetables"].replace({1:1,2:0})
data["Smoke100"] = data["Smoke100"].replace({1:1,2:0})
data["Stroke"] = data["Stroke"].replace({1:1,2:0})
data["HeartDisease"] = data["HeartDisease"].replace({1:1,2:0})
data["HighBp"] = data["HighBp"].replace({1:0,2:1})
data["HighCholesterol"] = data["HighCholesterol"].replace({2:0,1:1})
data["CheckedCholesterol"] = data["CheckedCholesterol"].replace({1:1,2:0})


# Now 0 represents the absence of a risk factor and 1 represents the presence of a risk factor across all binary columns.

In [ ]:
print(data.shape)
data["Diabetes"].value_counts()

## EDA

In [ ]:
df = data.copy()
# copy to work with for EDA and visualization.

### Understanding missingness

In [ ]:
# Percentage of missing values in each column
missing_counts = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    "Missing Count": missing_counts,
    "Missing %": missing_percent
}).sort_values(by="Missing %", ascending=False)

print(missing_df)

In [ ]:
# Droping rows that have missing values greater than or equal to 50% of the columns.
# they are just too incomplete to be useful and could introduce noise into the model.
threshold = len(df.columns) * 0.5
df["missing_row_count"] = df.isnull().sum(axis=1)
df = df[df["missing_row_count"] < threshold]
df.drop(columns=["missing_row_count"], inplace=True)

In [ ]:
# Visualizing missingvalues of columns with missing percentage greater than 5% to understand the distribution of missing data and its relationship with diabetes status.

plt.figure(figsize=(20, 25)) 

for i, column in enumerate(missing_df[missing_df["Missing %"] > 5].index):
    plt.subplot(5, 5, i + 1) 
    sns.countplot(x=df[column].isnull(), hue=df['Diabetes'])
    plt.title(column)
    plt.xticks([0, 1], ['Present', 'Missing']) 
plt.tight_layout()
plt.show()

these above missingness may be informative since there are high gaps for their missing values by diabetes

In [ ]:
plt.figure(figsize=(20,15))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.show()

- Some columns have clearly vertically stacked yellow lines implying missingness is column driven and not random across the dataset 
- Also no horizontal thick lines accross many columns implying remaining missingness is not row dependent (already removed them earlier ).
- Some columns also share missing pattern

**I'll classify the columns by their missingness based on the informations derived above** into "randomly_missing" and "structurally_missing" 
- **structurally_missing** (MAR):  will inpute but add flag 
- **randomly_missing** (MCAR): will only input

In [ ]:
structurally_missing = ["HighCholesterol","Income","BMI","Fruits",
                        "Vegetables","HeavyDrinking","PhysicalActivity"]
# everything else not structurally missing here is randomly missing

In [ ]:
# creating new binary columns to indicate whether the value is missing or not for structurally missing columns.
for col in structurally_missing:
    df[col +"Missing"] = df[col].isnull().astype(int)
df.columns

In [ ]:
# applying appropriate imputation strategies for each type of missing data
# CONTINUOUS 
for col in continuous_cols:
    df[col] = df[col].fillna(df[col].median())

# BINARY
for col in binary_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# ORDINAL
for col in ordinal_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
# checking unique values
uniques = {}
for col in df.columns:
    uniques[col] = df[col].nunique()

pd.DataFrame(uniques, index=['unique value count']).transpose()

### Target distribution

In [ ]:
# target distribution after cleaning
counts = df["Diabetes"].value_counts().sort_index()
plt.figure(figsize=(6,4))
plt.pie(counts, labels=["Non-Diabetic", "Diabetic"], autopct='%1.1f%%')
plt.title("Diabetes Distribution ")
plt.show()

Dataset is heavily imbalanced with more non diabetics than diabetics

### Continuous Features Analysis

In [ ]:
for col in continuous_cols:
    sns.histplot(df[col])
    plt.title(f"{col} Distribution")
    plt.show()

In [ ]:
# outliers
for col in continuous_cols:
    sns.boxplot(x=df[col])
    plt.title(f"{col} Boxplot")
    plt.show()

In [ ]:
# Relationship with diabetes
for col in continuous_cols:
    sns.boxplot(x=df["Diabetes"], y=df[col])
    plt.title(f"{col} vs Diabetes")
    plt.show()

All 3 features are skewed to the right with lots of outliers making median the correct choice for imputation.

Individuals with diabetes  have clearly higher median BMI, hence a wider spread , indicating a strong positive relationship between BMI and diabetes occurrence.

Diabetics report more physically unhealthy days although there is a significant overlap with non diabetics (only that theirs are outliers .)

Mental health shows weak relationship with diabetes, with similar distributions across both classes.”

**Already signifying slightly that physical health factors might better predict diabetics than mental health factors**

### Binary Features Analysis

In [ ]:
# Distribution

fig, axes = plt.subplots(nrows=5, ncols=3, figsize=(15, 20))

axes = axes.flatten()

for i, col in enumerate(binary_cols):
    sns.countplot(data=df, x=col, ax=axes[i])
    axes[i].set_title(f'{col} Distribution')

# Hide unused subplots 
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout() 
plt.show()

In [ ]:
# Relationship with target
fig, axes = plt.subplots(nrows=5, ncols=3, figsize=(15, 20))
axes = axes.flatten()

for i, col in enumerate(binary_cols):
    prop = pd.crosstab(df[col], df["Diabetes"], normalize="index")
    
    prop.plot(
        kind="bar",
        stacked=True,
        ax=axes[i]
    )
    
    axes[i].set_title(f"{col} Diabetes Percentage")
    axes[i].set_ylabel("Proportion")
    axes[i].set_xlabel(col)
    axes[i].legend(title="Diabetes")

# Hide unused plots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

In [ ]:
for col in binary_cols:
    prop = pd.crosstab(df[col], df["Diabetes"], normalize="index")
    print((prop * 100).round(2))
    print("\n")

Binary feature analysis revealed strong associations between health conditions and diabetes prevalence. 

Features such as High Blood Pressure, High Cholesterol, Heart Disease, Stroke, and Difficulty Walking showed significantly higher diabetes rates, indicating strong predictive potential. 

Lifestyle-related variables like Physical Activity,Fruits,Vegetables and smoke100 exhibited protective effects, while dietary indicators  and demographic variables like HealthCareAccess,MedicalCost,Heavy drinking and Sex showed minimal separation

### Ordinal Feature analysis

In [ ]:
fig, axes = plt.subplots(nrows=3, ncols=2, figsize=(15, 15))
axes = axes.flatten()

for i, col in enumerate(ordinal_cols):
    prop = pd.crosstab(df[col], df["Diabetes"], normalize="index")
    
    prop.plot(
        kind="bar",
        stacked=True,
        ax=axes[i]
    )
    
    axes[i].set_title(f"{col} vs Diabetes (Proportion)")
    axes[i].set_ylabel("Proportion")
    axes[i].set_xlabel(col)

# Hide unused plots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

In [ ]:
for col in ordinal_cols:
    prop = pd.crosstab(df[col], df["Diabetes"], normalize="index")
    print((prop * 100).round(2))
    print(f"\n")

Ordinal feature analysis revealed strong monotonic relationships with diabetes prevalence.

General health exhibited a clear inverse relationship, with poorer health strongly associated with higher diabetes rates.

Age showed a steady increase in diabetes risk across groups, confirming it as a key predictor.

Education and Income demonstrated decreasing diabetes prevalence with higher levels, suggesting indirect effects through lifestyle and healthcare access.

### Analyzing CheckedCholesterol

In [ ]:
prop = pd.crosstab(df["CheckedCholesterol"], df["Diabetes"], normalize="index")
print((prop * 100).round(2))

In [ ]:
prop.plot(kind="bar", stacked=True, figsize=(6,5))
plt.title("CheckedCholesterol vs Diabetes (Proportion)")
plt.ylabel("Proportion")
plt.xlabel("CheckedCholesterol")
plt.xticks(rotation=0)
plt.show()

Individuals who recently checked their cholesterol show higher diabetes prevalence,

Those who never checked exhibit lower observed diabetes rates, which may be influenced by underdiagnosis or lower interaction with healthcare systems. 

The “unknown” group shows elevated risk relative to the “never” category, suggesting potential hidden or uncertain health status.

### Correlation Analysis

In [ ]:
df2 = df.copy()

In [ ]:
# dataset without the missing flags 
df2.drop(columns=[f"{col}Missing" for col in df.columns if f"{col}Missing" in df.columns], inplace=True)

data - original dataset to be used for training 

df - copy of data ,used in EDA, has missing boolean binary column

df2 - without the missingcolumn

In [ ]:
df2.shape

In [ ]:
# one hot encoding for nominal variable CheckedCholesterol
df_encoded = pd.get_dummies(df2, drop_first=False)
corr = df_encoded.corr()

In [ ]:
df_encoded.head()

In [ ]:
# Heatmap of correlation 
plt.figure(figsize = (20,10))
sns.heatmap(corr, annot= True ,cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

Notables from the heatmap ,

Sex correlation with almost every feature including target  does not exceed 0.1 making it a  very low priority predictive feature  

General health, physical health, mental health and difficulty walking exhibit moderate intercorrelation with each other.

checked cholesterol recently exhibits some medial relation ship with Age, health care access,High bp  and high cholesterol , also a very high negative relationship with checked cholesterol never --as it should be 

checked cholesterol unknown correlation is very similar to that of of sex feature,with correlation values not exceeding 0.1  except with checked cholesterol recently.This implies that the unknown parameter in checked cholesterol does not significantly contribute in any way to the useful features and i can safely drop it.

### Missing Flags Analysis

In [ ]:
for col in structurally_missing:
    cross_tab = pd.crosstab(df["Diabetes"], df[f"{col}Missing"], normalize="index")*100

    cross_tab.plot(kind="bar", stacked=True, color=["#4C72B0", "#C44E52"], figsize=(8, 5))

    plt.title(f"{col}Missing Distribution by diabetes ")
    plt.ylabel("Percentage (%)")
    plt.xlabel("Diabetes")

    plt.legend(title="Missing Status", labels=["Present (0)", "Missing (1)"])
    plt.tight_layout()
    plt.show()
    print(f"Structural Missingness Distribution by Diabetes:\n {cross_tab}\n")

The differences between diabetic and non diabetic for the flags are minimal (less than 1%) of which their missingness truely appears to be missing completely at random (MCAR) with the exception of HichCholesterolMissing.

HighCholesterolMissing displayed a notable distribution difference, indicating potential informative missingness.

Now only HighCholesterol would remain in structurally_missing

In [ ]:
# droping flags whose structural missingness demonstrated negligible informational value.
structurally_missing = ["HighCholesterol"]

In [ ]:
# deleting unused data frames 
del df
del df_encoded
del df2

## Feature selection

In [ ]:
#  copy of data to work with for feature selection 
Feature = data.copy()
Feature.columns

In [ ]:
# importing necessary libraries for feature selection.
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.compose import ColumnTransformer 
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,RobustScaler
from sklearn.pipeline import Pipeline

In [ ]:
# missing flag for our structurally missing data   
for col in structurally_missing:
    Feature[f"{col}Missing"] = Feature[col].isnull().astype(int)
Feature.columns

In [ ]:
# defining features and target variables
X = Feature.drop(columns=["Diabetes"])
y = Feature["Diabetes"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)

In [ ]:
# Continuous pipeline
continuous_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", RobustScaler())
])

# Binary and Ordinal  pipeline 
binord_pipeline = Pipeline(steps=[
    ("imputer",SimpleImputer(strategy="most_frequent"))
])

# Nominal Pipeline 
nominal_pipeline = Pipeline(steps=[
    ("Encoder",OneHotEncoder(drop="first", handle_unknown="ignore",sparse_output=False))
])

preprocessor = ColumnTransformer(transformers=[
    ("continuous",continuous_pipeline,continuous_cols),
    ("binary",binord_pipeline,binary_cols),
    ("ordinal",binord_pipeline,ordinal_cols),
    ("nominal",nominal_pipeline,nominal_cols)
],remainder="passthrough")

In [ ]:
# Transforming the data
X_train_clean = preprocessor.fit_transform(X_train)
X_test_clean = preprocessor.transform(X_test)

# Get feature names
feature_names = preprocessor.get_feature_names_out()

# train
RF_selector = RandomForestClassifier(random_state=1)
RF_selector.fit(X_train_clean, y_train)

In [ ]:
# renaming the feature names from the preprocessor  properly
feature_list = []
for names in feature_names:
    before,delimeter,after = names.partition("__")
    feature_list.append(after)
features = np.array(feature_list)
features

In [ ]:
#  DataFrame of features sorted by importance
importance_df = pd.DataFrame({
    "Feature":features,
    "Importance": RF_selector.feature_importances_
},).sort_values(by="Importance", ascending=False).reset_index(drop=True)

# Normalized importance 
importance_df["Normalized Importance"] = (importance_df["Importance"] - importance_df["Importance"].min()) / (importance_df["Importance"].max() - importance_df["Importance"].min())

# cummulative importance
importance_df["Cummulative Importance"] = importance_df["Normalized Importance"].cumsum()

# treshold for selecting features (i choose features within 85% of cummulative predicting power )
treshold = 0.85

#  Filter rows. We shift the threshold boundary by one to include the final boundary feature that pushes the cumulative sum over 85%.
selected_df = df[df["Cummulative Importance"].shift(1, fill_value=0) < threshold]
selected_features = selected_df["Feature"].to_numpy()

In [ ]:
# Creating a seaborn bar plot

fig, ax = plt.subplots(figsize=(30, 24))
ax = sns.barplot(x=importance_df["Importance"], y=importance_df["Features"], data=importance_df)
ax.set_title("Visualize feature scores of the features")
ax.set_yticklabels(importance_df["Features"])
ax.set_xlabel("Feature importance score")
ax.set_ylabel("Features")
plt.show()